### ISSUE TITLE
Подобрать шрифт с кирилицей

### ISSUE THREAD

**Issue by alek13** [lord-server/lord-server.ru#1]
Используемый сейчас шрифт `Titillium` не имеет кирилицы.
Подставлен `Arial`, как самый близкий, но всё равно выглядит по разному

**Comment by Doloment** [comment]
Предлагаю использовать `Calibri`. Чем-то похож на `Titillium`, но имеет кириллицу.

**Comment by weqqr** [comment]
https://fonts.google.com/

**Comment by alek13** [comment]
не актуально, старая версия больше не будет поддерживаться, только мелкие правки типа "поменять состав кланов"
